### ISSUE TITLE
Add an autoload/checkhealth ?

### ISSUE THREAD

**Issue by michaelb** [gennaro-tedesco/boilit#1]
checkhealth is a neat feature that can tremendously help debugging what goes wrong.

I think all but the smallest plugins have something to check, be it only that they're up to date (something that's not trivial to do in vimscript/lua) but sometimes that an external dependency is installed or a ressource is present.

**Comment by gennaro-tedesco** [comment]
Are you referring to the `:checkhealth` neovim command or did I misunderstand? Or perhaps you could show an example of what you would like to see/implement so that I understand better :)

**Comment by michaelb** [comment]
I was indeed referring to the `:checkhealth` feature, but wasn't fully awake yet. The following is (i hope) more correct and accurate.


Most of the modern plugin advanced enough to care about checkhealth are written in lua, so the content in `autoload/health/<plugin_name>.vim` is usually

```
function health#<plugin_name>#check()
  lua require'<plugin_name>'.health()
endfunction
```
My own plugin.health() looks like this (the formatting is terrible and i have little time right now ,sorry)
<details>
<code>

function M.health()

  local health_start = vim.fn["health#report_start"]

  local health_ok = vim.fn['health#report_ok']
  
  local health_error = vim.fn['health#report_error']
  
  local health_warn = vim.fn['health#report_warn']
  
  health_start('Installation')
  
  if vim.fn.executable('tree-sitter') == 0 then

      health_warn('"tree-sitter" executable not found (parser generator, only needed for 

  :TSInstallFromGrammar,'..
                ' not required for :TSInstall)')
  
  else
  
    local handle = io.popen('tree-sitter  -V')
  
    local result = handle:read("*a")
  
    handle:close()
  
    local version = vim.split(result,'\n')[1]:match('[^tree%psitter].*')
  
    health_ok('"tree-sitter" found '..version..' (parser generator, only needed for :
  TSInstallFromGrammar)')
  
  end

  if vim.fn.executable(binary_path) == 0 then health_error("sniprun binary not found!")
  
  else health_ok("sniprun binary found") end


  if vim.fn.executable('cargo') == 0 then health_warn("Rust toolchain not available", {"[optionnal] Install the rust toolchain https://www.rust-lang.org/tools/install"})
  
else health_ok("Rust toolchain found") end

end

</code>
</details>


Non-lua, or just simpler plugins will often implement `checkhealth` as documented [here](https://neovim.io/doc/user/pi_health.html)

Many plugins could and should check basic things such as (simplified version)
```
function health#plugin_name#check()
    if !has('minimum nvim version') then
        health_report_error("Nvim too old")
    else
         health_report_ok("nvim recent enough")
    endif
    if !executable('ruby') then
        health_report_warn("Optionnal dependency ruby is not installed")
    endif
endfunction
```

**Comment by gennaro-tedesco** [comment]
I understand now a little better what you meant, yes, it makes sense. I will try and implement something along the lines indicated in the docs - it may take a few days (I am a little busy today and want to think about it more thoroughly); I will then prepare a pull request and you may help reviewing it.

In general, though, some of those health checks are quite implementation-specific (say check for versions of a specific language/program being available or so), therefore for a boilerplate utility like this one only general checks would make sense (checking neovim version or some general paths). What can general checks look like besides nvim version or nvim runpaths?

**Comment by michaelb** [comment]
While such 'checks' are specific to plugins, generating a boilerplate that always report ok, but has 1 or 2 commented if branches explaining how to report a missing dependency or something would probably be welcome.

Take the time you need ofc, I'll gladly review some Go, it has been a while

**Comment by gennaro-tedesco** [comment]
I have drafted a pull request [here](https://github.com/gennaro-tedesco/boilit/pull/5/files). 

The bulk of it is that I am adding a boiler `lua/health.lua` file containg
```
local function checkhealth()
   if vim.fn.has('nvim-0.5') then
	  vim.fn['health#report_ok']('nightly installed')
   else
	  vim.fn['health#report_warn']('install neovim nightly')
   end

   -- check more health conditions here
--[[    if vim.fn.executable('lua') ~= 1 then
	  vim.fn['health#report_error']('lua not installed')
   end ]]
end

return {
   checkhealth = checkhealth,
}
```
that is called in `autoload/<plugin_name>/health.vim`. This generates something along the lines of
```
health#nvimtest#check
========================================================================
  - OK: nightly installed
```
when running the healthcheck.

1. About the Go part: the way I create these templates is shown [here](https://github.com/gennaro-tedesco/boilit/blob/ceb90a2a2ca74d816bedd933da927031081b995f/cmd/boilerplate.go#L126-L193), for example. Notice that being relatively new to Go I may be doing some outrageous practices, so feel free to suggest a better way to write long strings to files. 
2. About the Vim healthcheck: the function is just a skeleton, we may add more (commented out) statements if you deem them insufficient.

**Comment by gennaro-tedesco** [comment]
This has been included in the release [1.1.0](https://github.com/gennaro-tedesco/boilit/releases)

**Comment by hoschi** [comment]
I installed the current version via `go` as stated in the Readme and created my plugin, but can't see the `autoload` dir.

**Comment by gennaro-tedesco** [comment]
Are you sure you installed the latest release with `go get -u -v`? See below:


https://user-images.githubusercontent.com/15387611/127745190-f0c63bf9-5039-4426-8c54-7ff6738dbfa3.mov

[This is the release](https://github.com/gennaro-tedesco/boilit/releases/tag/v.1.1.0) where `autoload` was included, in particular it happens [here in the code](https://github.com/gennaro-tedesco/boilit/blob/84337a9720a22830b53d6ad8e93759dfa66ffa27/cmd/boilerplate.go#L107). I suspect `go get` did not fetch the latest version; alternatively you could try installing the latest release explicitly and running the code from source (to validate that the code does indeed work).

**Comment by hoschi** [comment]
Strange, I did the same thing! I'm going to look into it

**Comment by hoschi** [comment]
How do I remove packages installed with `go get`? How can I see the release number of the `boilit` bin after installing?

**Comment by gennaro-tedesco** [comment]
> How do I remove packages installed with go get?

you can directly remove the binaries that are installed in `go/bin`; in particular they should be located in
```
$ which boilit
~/go/bin/boilit
```
just remove it.

> How can I see the release number of the boilit bin after installing?

At the moment there is no command to print out the `--version`: in fact this is a good suggestion and I will add it. For the moment though please check if installing again with `go get -u -v` gives you the correct results, alternatively installing from source (so that I can make the changes all together should there be any bugs).

**Comment by hoschi** [comment]
It works when I start it from source.

**Comment by gennaro-tedesco** [comment]
This means that the problem lies in your local `go` installation that does not fetch the updated dependencies with `go get -u -v`. Are all your go environment variables in the right place (what is the value of your `GO111MODULE`?)

**Comment by hoschi** [comment]
I'm out, sorry for the noise.
