### ISSUE TITLE
Problem on running

### ISSUE THREAD

**Issue by mthnglac** [gennaro-tedesco/boilit#2]
There is some problem on running boilit after installation.
```bash
boilit nvim-awesome-plugin
```
after installation i cannot execute the command below:
```bash
boilit nvim-awesome-plugin
```

**Comment by gennaro-tedesco** [comment]
> after installation i cannot execute the command below:

are you seeing an error when executing such command or what happens exactly?

**Comment by mthnglac** [comment]
```bash
command not found: boilit
```

**Comment by gennaro-tedesco** [comment]
This means that the program wasn't installed. What does `$ which boilit` return? You should see something along the lines of
```
which boilit
~/go/bin/boilit 
```
Likewise 
```
go env | grep GOPATH
GOPATH="~/go"
```
could you check all this is in place?

**Comment by mthnglac** [comment]
There was no problem installing the program. I think there is something about PATH. I solved the problem with the command:
```bash
~/go/bin/boilit nvim-awesome-plugin
```
Thanks for your help.
